use_frameworks!

platform :ios, '8.0'

target 'CustomAlert_Example' do
  pod 'CustomAlert', :path => '../'

  target 'CustomAlert_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
